buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // 升级插件版本以匹配较新的 Gradle
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
